const express = require('express')
const cors = require('cors')
const app = express()
app.use(cors())
app.use(express.json({ strict: false }))
app.use(express.urlencoded({ extended: true }))
app.use((req,res,next)=>{console.log('Body:',req.body);next()})
const authRoutes = require('./src/routes/auth')
app.use('/api/auth', authRoutes)
const storeRoutes = require('./src/routes/stores')
app.use('/api/stores', storeRoutes)
const productRoutes = require('./src/routes/products')
app.use('/api/products', productRoutes)
const orderRoutes = require('./src/routes/orders')
app.use('/api/orders', orderRoutes)
const paymentRoutes = require('./src/routes/payments')
app.use('/api/payments', paymentRoutes)
app.get('/',(req,res)=>res.json({message:'Dukkan API is running!'}))
app.listen(5000,()=>console.log('Server running on port 5000'))
